name: Coding Standards
on: [ push, pull_request ]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Code style checks for PHP and CSS
        run: |
          composer install
          npm ci
          composer lint-all
