name: Plugin check
on:
  push:
    branches: [ 'release/*' ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Build
        run:  composer install --no-interaction

      - name: Package plugin
        run: |
          mkdir -p ./dist
          rsync -rc --exclude-from=.distignore ./ ./dist/snitch --delete --delete-excluded

      - name: Check WP plugin
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: ./dist/snitch
